# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: youshouldeditthis 	# 博客名
subtitle: youshouldeditthis 	# 副标题
description: youshouldeditthis 	# description，用于搜索
author: youshouldeditthis 	# 作者
language: zh-Hans 	# 语言
timezone: 	# 时区，默认为系统时区

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: youshouldeditthis 	# 博客 url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# 跳过，不编译，主要用于站长平台验证文件
skip_render:
  - youshouldeditthis
  - youshouldeditthis
# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

menu:
  home: /
  archives: /archives
  tags: /tags
  categories: /categories

favicon: /favicon.ico
avatar: /default_avatar.png
fancybox: true

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: youshouldeditthis # github git 地址
  branch: master

# 配置 404 页
handle:
 errordoc: 404 /404.html